# Generated by Django 4.2.7 on 2025-11-08 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sentiment_score', models.FloatField()),
                ('burnout_risk', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_sentiments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('month', 'Employee of the Month'), ('year', 'Employee of the Year'), ('attendance', 'Best Attendance'), ('team', 'Team Player')], max_length=20)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttritionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('factors', models.JSONField(default=dict)),
                ('recommendation', models.TextField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attrition_risks',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
