# Generated by Django 5.2.8 on 2025-11-08 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('predicted_absent', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('factors', models.JSONField()),
                ('actual_status', models.CharField(blank=True, max_length=20, null=True)),
                ('accuracy', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_attendance_prediction',
                'indexes': [models.Index(fields=['employee', 'date'], name='analytics_a_employe_fb0539_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttritionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('tenure_months', models.IntegerField()),
                ('leaves_trend', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('salary_percentile', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_attrition_risk',
                'indexes': [models.Index(fields=['employee'], name='analytics_a_employe_c8daa7_idx'), models.Index(fields=['risk_level'], name='analytics_a_risk_le_6756c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('month', 'Employee of the Month'), ('year', 'Employee of the Year'), ('team', 'Team Player Award'), ('attendance', 'Perfect Attendance')], max_length=20)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_employee_award',
                'indexes': [models.Index(fields=['year', 'month'], name='analytics_e_year_e4236c_idx'), models.Index(fields=['award_type'], name='analytics_e_award_t_a1d745_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('average_sentiment_score', models.FloatField()),
                ('sentiment_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20)),
                ('high_risk_keywords_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_employee_sentiment',
                'indexes': [models.Index(fields=['employee', 'year'], name='analytics_e_employe_9112fc_idx'), models.Index(fields=['sentiment_trend'], name='analytics_e_sentime_56115e_idx')],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
