# Generated by Django 5.2.8 on 2025-11-08 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('half-day', 'Half Day'), ('work-from-home', 'Work From Home')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overtime_approved', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'hr_officer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_attendance',
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['employee', '-date'], name='attendance__employe_189149_idx'), models.Index(fields=['status', 'date'], name='attendance__status_a2ceef_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_timestamp', models.DateTimeField(blank=True, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('verification_confidence', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comp_off_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('comp_off_claimed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_overtime',
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_203f9a_idx'), models.Index(fields=['status', 'date'], name='attendance__status_d4370a_idx')],
            },
        ),
    ]
