# Generated by Django 5.2.8 on 2025-11-08 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_document_fingerprint',
                'indexes': [models.Index(fields=['fingerprint'], name='sync_docume_fingerp_4576a8_idx'), models.Index(fields=['document_type', 'document_id'], name='sync_docume_documen_737838_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.CharField(max_length=255)),
                ('synced_from', models.CharField(max_length=20)),
                ('synced_to', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('data_size_bytes', models.IntegerField()),
                ('sync_duration_ms', models.IntegerField()),
                ('error_message', models.TextField(blank=True)),
                ('conflict_detected', models.BooleanField(default=False)),
                ('conflict_resolution_method', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_sync_log',
                'indexes': [models.Index(fields=['user', '-timestamp'], name='sync_sync_l_user_id_d1c205_idx'), models.Index(fields=['status', 'timestamp'], name='sync_sync_l_status_927740_idx'), models.Index(fields=['conflict_detected'], name='sync_sync_l_conflic_e850e9_idx')],
            },
        ),
    ]
