# Generated by Django 5.2.8 on 2025-11-08 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('annual_allocation', models.IntegerField()),
                ('is_carryforward_allowed', models.BooleanField(default=False)),
                ('max_carryforward', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'leaves_leave_type',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('casual_allocated', models.IntegerField(default=12)),
                ('casual_used', models.IntegerField(default=0)),
                ('casual_carryforward', models.IntegerField(default=0)),
                ('sick_allocated', models.IntegerField(default=8)),
                ('sick_used', models.IntegerField(default=0)),
                ('personal_allocated', models.IntegerField(default=5)),
                ('personal_used', models.IntegerField(default=0)),
                ('earned_leave_allocated', models.IntegerField(default=5)),
                ('earned_leave_used', models.IntegerField(default=0)),
                ('total_allocated', models.IntegerField(default=30)),
                ('total_used', models.IntegerField(default=0)),
                ('total_available', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_leave_balance',
                'indexes': [models.Index(fields=['employee', 'year'], name='leaves_leav_employe_12b3ec_idx')],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('earned', 'Earned Leave')], db_index=True, max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('sentiment_score', models.FloatField(default=0, help_text='Sentiment analysis of leave reason (-1 to 1)')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('burnout_risk_detected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_leave_request',
                'indexes': [models.Index(fields=['employee', 'status'], name='leaves_leav_employe_c8182c_idx'), models.Index(fields=['employee', '-start_date'], name='leaves_leav_employe_5d5949_idx'), models.Index(fields=['status', 'created_at'], name='leaves_leav_status_c39a09_idx'), models.Index(fields=['burnout_risk_detected'], name='leaves_leav_burnout_282970_idx')],
            },
        ),
    ]
