# Generated by Django 5.2.8 on 2025-11-08 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_attendance', models.IntegerField(default=75)),
                ('min_tenure_months', models.IntegerField(default=6)),
                ('month_applicable', models.IntegerField(help_text='Month when bonus is paid (1-12)')),
            ],
            options={
                'db_table': 'payroll_bonus_policy',
            },
        ),
        migrations.CreateModel(
            name='Payrun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('finalized', 'Finalized')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'payroll_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_payrun',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.IntegerField(default=26)),
                ('days_worked', models.IntegerField()),
                ('leaves_taken', models.IntegerField()),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fingerprint', models.CharField(max_length=64, null=True, unique=True)),
                ('fingerprint_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrun')),
            ],
            options={
                'db_table': 'payroll_payslip',
            },
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['month', 'year'], name='payroll_pay_month_97ff76_idx'),
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['status'], name='payroll_pay_status_d1d1b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrun',
            unique_together={('month', 'year')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'payrun'], name='payroll_pay_employe_414c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payrun'], name='payroll_pay_payrun__210eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['fingerprint'], name='payroll_pay_fingerp_5239e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payrun', 'employee')},
        ),
    ]
